// https://varletjs.github.io/varlet-theme-builder/
// https://varletjs.org/#/zh-CN/themes
export const MyGlobalTheme1 =
  {
    "light": {
      "--hsl-primary": "7, 100%, 37%",
      "--color-primary": "hsla(var(--hsl-primary), 1)",
      "--hsl-on-primary": "0, 0%, 100%",
      "--color-on-primary": "hsla(var(--hsl-on-primary), 1)",
      "--hsl-primary-container": "8, 100%, 92%",
      "--color-primary-container": "hsla(var(--hsl-primary-container), 1)",
      "--hsl-on-primary-container": "3, 100%, 12%",
      "--color-on-primary-container": "hsla(var(--hsl-on-primary-container), 1)",
      "--hsl-info": "9, 20%, 39%",
      "--color-info": "hsla(var(--hsl-info), 1)",
      "--hsl-on-info": "0, 0%, 100%",
      "--color-on-info": "hsla(var(--hsl-on-info), 1)",
      "--hsl-info-container": "8, 100%, 92%",
      "--color-info-container": "hsla(var(--hsl-info-container), 1)",
      "--hsl-on-info-container": "9, 44%, 12%",
      "--color-on-info-container": "hsla(var(--hsl-on-info-container), 1)",
      "--hsl-warning": "42, 41%, 31%",
      "--color-warning": "hsla(var(--hsl-warning), 1)",
      "--hsl-on-warning": "0, 0%, 100%",
      "--color-on-warning": "hsla(var(--hsl-on-warning), 1)",
      "--hsl-warning-container": "41, 89%, 82%",
      "--color-warning-container": "hsla(var(--hsl-warning-container), 1)",
      "--hsl-on-warning-container": "42, 100%, 7%",
      "--color-on-warning-container": "hsla(var(--hsl-on-warning-container), 1)",
      "--hsl-danger": "0, 75%, 42%",
      "--color-danger": "hsla(var(--hsl-danger), 1)",
      "--hsl-on-danger": "0, 0%, 100%",
      "--color-on-danger": "hsla(var(--hsl-on-danger), 1)",
      "--hsl-danger-container": "6, 100%, 92%",
      "--color-danger-container": "hsla(var(--hsl-danger-container), 1)",
      "--hsl-on-danger-container": "358, 100%, 13%",
      "--color-on-danger-container": "hsla(var(--hsl-on-danger-container), 1)",
      "--hsl-body": "0, 0%, 100%",
      "--color-body": "hsla(var(--hsl-body), 1)",
      "--hsl-text": "9, 12%, 11%",
      "--color-text": "hsla(var(--hsl-text), 1)",
      "--hsl-on-surface-variant": "9, 13%, 29%",
      "--color-on-surface-variant": "hsla(var(--hsl-on-surface-variant), 1)",
      "--hsl-outline": "9, 9%, 48%",
      "--color-outline": "hsla(var(--hsl-outline), 1)",
      "--hsl-inverse-surface": "13, 9%, 19%",
      "--color-inverse-surface": "hsla(var(--hsl-inverse-surface), 1)"
    },
    "dark": {
      "--hsl-primary": "9, 100%, 83%",
      "--color-primary": "hsla(var(--hsl-primary), 1)",
      "--hsl-on-primary": "4, 100%, 20%",
      "--color-on-primary": "hsla(var(--hsl-on-primary), 1)",
      "--hsl-primary-container": "6, 100%, 28%",
      "--color-primary-container": "hsla(var(--hsl-primary-container), 1)",
      "--hsl-on-primary-container": "8, 100%, 92%",
      "--color-on-primary-container": "hsla(var(--hsl-on-primary-container), 1)",
      "--hsl-info": "10, 51%, 81%",
      "--color-info": "hsla(var(--hsl-info), 1)",
      "--hsl-on-info": "10, 30%, 21%",
      "--color-on-info": "hsla(var(--hsl-on-info), 1)",
      "--hsl-info-container": "9, 23%, 30%",
      "--color-info-container": "hsla(var(--hsl-info-container), 1)",
      "--hsl-on-info-container": "8, 100%, 92%",
      "--color-on-info-container": "hsla(var(--hsl-on-info-container), 1)",
      "--hsl-warning": "41, 54%, 71%",
      "--color-warning": "hsla(var(--hsl-warning), 1)",
      "--hsl-on-warning": "44, 88%, 13%",
      "--color-on-warning": "hsla(var(--hsl-on-warning), 1)",
      "--hsl-warning-container": "44, 55%, 22%",
      "--color-warning-container": "hsla(var(--hsl-warning-container), 1)",
      "--hsl-on-warning-container": "41, 89%, 82%",
      "--color-on-warning-container": "hsla(var(--hsl-on-warning-container), 1)",
      "--hsl-danger": "6, 100%, 84%",
      "--color-danger": "hsla(var(--hsl-danger), 1)",
      "--hsl-on-danger": "357, 100%, 21%",
      "--color-on-danger": "hsla(var(--hsl-on-danger), 1)",
      "--hsl-danger-container": "356, 100%, 29%",
      "--color-danger-container": "hsla(var(--hsl-danger-container), 1)",
      "--hsl-on-danger-container": "6, 100%, 84%",
      "--color-on-danger-container": "hsla(var(--hsl-on-danger-container), 1)",
      "--hsl-body": "9, 12%, 11%",
      "--color-body": "hsla(var(--hsl-body), 1)",
      "--hsl-text": "11, 31%, 90%",
      "--color-text": "hsla(var(--hsl-text), 1)",
      "--hsl-on-surface-variant": "9, 25%, 80%",
      "--color-on-surface-variant": "hsla(var(--hsl-on-surface-variant), 1)",
      "--hsl-outline": "8, 11%, 58%",
      "--color-outline": "hsla(var(--hsl-outline), 1)",
      "--hsl-inverse-surface": "11, 31%, 90%",
      "--color-inverse-surface": "hsla(var(--hsl-inverse-surface), 1)"
    }
  }



export const MyGlobalTheme2 =
  {
    "light": {
      "--hsl-primary": "7, 100%, 37%",
      "--color-primary": "hsla(var(--hsl-primary), 1)",
      "--hsl-on-primary": "0, 0%, 100%",
      "--color-on-primary": "hsla(var(--hsl-on-primary), 1)",
      "--hsl-primary-container": "8, 100%, 92%",
      "--color-primary-container": "hsla(var(--hsl-primary-container), 1)",
      "--hsl-on-primary-container": "3, 100%, 12%",
      "--color-on-primary-container": "hsla(var(--hsl-on-primary-container), 1)",
      "--hsl-info": "9, 20%, 39%",
      "--color-info": "hsla(var(--hsl-info), 1)",
      "--hsl-on-info": "0, 0%, 100%",
      "--color-on-info": "hsla(var(--hsl-on-info), 1)",
      "--hsl-info-container": "8, 100%, 92%",
      "--color-info-container": "hsla(var(--hsl-info-container), 1)",
      "--hsl-on-info-container": "9, 44%, 12%",
      "--color-on-info-container": "hsla(var(--hsl-on-info-container), 1)",
      "--hsl-warning": "42, 41%, 31%",
      "--color-warning": "hsla(var(--hsl-warning), 1)",
      "--hsl-on-warning": "0, 0%, 100%",
      "--color-on-warning": "hsla(var(--hsl-on-warning), 1)",
      "--hsl-warning-container": "41, 89%, 82%",
      "--color-warning-container": "hsla(var(--hsl-warning-container), 1)",
      "--hsl-on-warning-container": "42, 100%, 7%",
      "--color-on-warning-container": "hsla(var(--hsl-on-warning-container), 1)",
      "--hsl-danger": "0, 75%, 42%",
      "--color-danger": "hsla(var(--hsl-danger), 1)",
      "--hsl-on-danger": "0, 0%, 100%",
      "--color-on-danger": "hsla(var(--hsl-on-danger), 1)",
      "--hsl-danger-container": "6, 100%, 92%",
      "--color-danger-container": "hsla(var(--hsl-danger-container), 1)",
      "--hsl-on-danger-container": "358, 100%, 13%",
      "--color-on-danger-container": "hsla(var(--hsl-on-danger-container), 1)",
      "--hsl-body": "300, 100%, 99%",
      "--color-body": "hsla(var(--hsl-body), 1)",
      "--hsl-text": "9, 12%, 11%",
      "--color-text": "hsla(var(--hsl-text), 1)",
      "--hsl-on-surface-variant": "9, 13%, 29%",
      "--color-on-surface-variant": "hsla(var(--hsl-on-surface-variant), 1)",
      "--hsl-outline": "9, 9%, 48%",
      "--color-outline": "hsla(var(--hsl-outline), 1)",
      "--hsl-inverse-surface": "13, 9%, 19%",
      "--color-inverse-surface": "hsla(var(--hsl-inverse-surface), 1)"
    },
    "dark": {
      "--hsl-primary": "9, 100%, 83%",
      "--color-primary": "hsla(var(--hsl-primary), 1)",
      "--hsl-on-primary": "4, 100%, 20%",
      "--color-on-primary": "hsla(var(--hsl-on-primary), 1)",
      "--hsl-primary-container": "6, 100%, 28%",
      "--color-primary-container": "hsla(var(--hsl-primary-container), 1)",
      "--hsl-on-primary-container": "8, 100%, 92%",
      "--color-on-primary-container": "hsla(var(--hsl-on-primary-container), 1)",
      "--hsl-info": "10, 51%, 81%",
      "--color-info": "hsla(var(--hsl-info), 1)",
      "--hsl-on-info": "10, 30%, 21%",
      "--color-on-info": "hsla(var(--hsl-on-info), 1)",
      "--hsl-info-container": "9, 23%, 30%",
      "--color-info-container": "hsla(var(--hsl-info-container), 1)",
      "--hsl-on-info-container": "8, 100%, 92%",
      "--color-on-info-container": "hsla(var(--hsl-on-info-container), 1)",
      "--hsl-warning": "41, 54%, 71%",
      "--color-warning": "hsla(var(--hsl-warning), 1)",
      "--hsl-on-warning": "44, 88%, 13%",
      "--color-on-warning": "hsla(var(--hsl-on-warning), 1)",
      "--hsl-warning-container": "44, 55%, 22%",
      "--color-warning-container": "hsla(var(--hsl-warning-container), 1)",
      "--hsl-on-warning-container": "41, 89%, 82%",
      "--color-on-warning-container": "hsla(var(--hsl-on-warning-container), 1)",
      "--hsl-danger": "6, 100%, 84%",
      "--color-danger": "hsla(var(--hsl-danger), 1)",
      "--hsl-on-danger": "357, 100%, 21%",
      "--color-on-danger": "hsla(var(--hsl-on-danger), 1)",
      "--hsl-danger-container": "356, 100%, 29%",
      "--color-danger-container": "hsla(var(--hsl-danger-container), 1)",
      "--hsl-on-danger-container": "6, 100%, 84%",
      "--color-on-danger-container": "hsla(var(--hsl-on-danger-container), 1)",
      "--hsl-body": "9, 12%, 11%",
      "--color-body": "hsla(var(--hsl-body), 1)",
      "--hsl-text": "11, 31%, 90%",
      "--color-text": "hsla(var(--hsl-text), 1)",
      "--hsl-on-surface-variant": "9, 25%, 80%",
      "--color-on-surface-variant": "hsla(var(--hsl-on-surface-variant), 1)",
      "--hsl-outline": "8, 11%, 58%",
      "--color-outline": "hsla(var(--hsl-outline), 1)",
      "--hsl-inverse-surface": "11, 31%, 90%",
      "--color-inverse-surface": "hsla(var(--hsl-inverse-surface), 1)"
    }
  }

